### PR TITLE
webcord: bump to 4.1.1

### PR DESCRIPTION
**Pull request by rubyowo**

### CODE REVIEW

**Comment by fufexan** [comment]
Could you update again (to 4.1.1)?

**Comment by rubyowo** [comment]
sure

**Comment by rubyowo** [comment]
is there any reason why it's not installing the dependencies? or does it not matter

**Comment by fufexan** [comment]
No idea, something's broken upstream. Let's just wait until next release I guess. This has also been an issue when I wanted to update to 3.9.0.

**Pull request closed without merging**
